---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/sdk
    tag: 5.0.103-alpine3.12-amd64
inputs:
- name: source
params:
  PROJECT:
run:
  path: /bin/sh
  args:
  - -c
  - |
    cd "source/${PROJECT}"
    dotnet build /p:GeneratePackageOnBuild=False -c Release "${PROJECT}.csproj"
