---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/core/sdk
    tag: 3.1
inputs:
- name: source
- name: version

params:
  NUGGET_API_KEY: ((nugget_api_key))
  PROJECT:
  NUGGET_TAGS:

run:
  path: /bin/sh
  args:
  - -c
  - -e
  - |
    VERSION=$(cat version/version)
    cd "source/${PROJECT}"
    dotnet build /p:GeneratePackageOnBuild=False /p:AssemblyVersion=${VERSION} /p:FileVersion=${VERSION} -c Release "${PROJECT}.csproj"
    dotnet pack /p:PackageVersion=${VERSION} /p:PackageTags="${NUGGET_TAGS} $(cat ../.git/ref)" /p:PackageReleaseNotes="$(cat ../.git/commit_message)" --no-restore -c Release -o out "${PROJECT}.csproj"
    dotnet nuget push out/${PROJECT}.${VERSION}.nupkg -k ${NUGGET_API_KEY} -s https://api.nuget.org/v3/index.json
